apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-container
        image: alindor185/todo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: "mongodb://host.docker.internal:27017/mydb"
