pipeline {
  agent any

  stages {
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t myapp:latest .'
      }
    }
    stage('Push Docker Image') {
      steps {
        sh 'docker push myapp:latest'
      }
    }
    stage('Deploy to Kubernetes') {
      steps {
        sh 'kubectl set image deployment/...'
      }
    }
  }
}
