pipeline {
  agent any

  environment {
    IMAGE_NAME = "alindor185/todo"
    TAG = "${BUILD_NUMBER}"
  }

  stages {
    stage('Build Docker Image') {
      steps {
        echo "Building Docker image..."
        sh 'docker build -t $IMAGE_NAME:$TAG .'
      }
    }

    stage('Push Docker Image to DockerHub') {
      steps {
        echo "Pushing Docker image..."
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh '''
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME:$TAG
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        echo "Deploying to Kubernetes..."
        sh 'kubectl set image deployment/todo-deployment todo-container=$IMAGE_NAME:$TAG --namespace=default'
      }
    }
  }
}
